version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - go-data:/go

  db:
    image: postgres:latest
    container_name: postgre
    environment:
      POSTGRES_DB: 'portfolio'
      POSTGRES_PASSWORD: 'Xshion0912'
      POSTGRES_USER: 'shion0625'
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data

volumes:
  go-data:

